name: cea-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cmake
  - cython
  - gcc=16.1
  - gfortran=16.1
  - gxx=16.1
  - m2-m4
  - make
  - ninja
  - numpy
  - pytest
  - python
  - setuptools
